map/urls.py
from django.urls import path

from . import views

app_name = "map"

urlpatterns = [
    path("", views.search, name="search"),
    path("detail/", views.search_detail, name="search_detail"),
    path("result/", views.search_result, name="search_result"),
    path('send_location/', views.receive_location, name='send_location'),
    path('get_location/', views.get_location, name='get_location'),
]

studyhub/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("timer/", include("timer.urls")),
    path("search/", include("map.urls")),
    path("todo/", include("todo.urls")),
    path("", include("user.urls")),
]

timer/urls.py
from django.urls import path

from . import views

app_name = "timer"

urlpatterns = [
    path("update/", views.update_settime, name="update"),
    path("save/", views.save_time, name="save"),
]

todo/urls.py
from django.urls import path
from .views import (
    tasklist_view,
    taskdetail_view,
    taskcreate_view,
    taskdelete_view,
    taskedit_view,
    statusedit_view,
    tasksearch_view,
)


urlpatterns = [
    path("", tasklist_view, name="task_list"),
    path("<int:id>/", taskdetail_view, name="task_detail"),
    path("form/", taskcreate_view, name="task_create"),
    path("delete/<int:id>/", taskdelete_view, name="task_delete"),
    path("edit/<int:id>/", taskedit_view, name="task_edit"),
    path("status/<int:id>/", statusedit_view, name="status_edit"),
    path("task/search/", tasksearch_view, name="task_search"),
]

todo/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Tasks(models.Model):

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE
    )  # Userが削除されたら削除
    title = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True)

    class Meta:
        verbose_name_plural = "Tasks"

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Tasks


class TaskForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ["title", "description", "is_completed", "deadline"]

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tasks
from .forms import TaskForm


# タスク一覧取得
def tasklist_view(request):
    # 現在ログインしているユーザーに関連するタスクを選択
    # select_relatedを使って、tasksに関連するuser情報も一度に取得する（クエリ数を減らすため）
    tasks = (
        Tasks.objects.select_related("user")
        .filter(user=request.user)
        .order_by("deadline")
    )
    return render(request, "todo.html", {"tasks": tasks})


# タスク詳細取得
def taskdetail_view(request, id):
    # Tasksテーブルからidが一致し、かつuserがログイン中のユーザーのタスクを取得する。
    # データが存在しない場合は自動的に「404エラー」
    task = get_object_or_404(Tasks, id=id, user=request.user)
    return render(request, "tododetail.html", {"task": task})


# タスク作成
def taskcreate_view(request):
    if not request.user.is_authenticated:
        return redirect("login")  # 未ログインの場合はログインページにリダイレクト

    if request.method == "POST":  # フォームがPOSTで送信されたとき
        form = TaskForm(request.POST)  # フォームにPOSTデータを渡してインスタンス作成
        if form.is_valid():  # フォームのバリデーションが成功した場合
            task = form.save(commit=False)  # データベースに保存
            task.user = request.user  # 現在ログインしているユーザーをタスクに関連付け
            task.save()
            return redirect("task_list")  # 一覧ページにリダイレクト
        else:
            return render(request, "todoform.html", {"form": form})
    else:
        form = TaskForm()  # フォームが送信されていない場合、空のフォームを表示

    return render(request, "todoform.html", {"form": form})


# タスク削除
def taskdelete_view(request, id):
    if not request.user.is_authenticated:
        return redirect("login")  # 未ログインならログインページへリダイレクト

    task = get_object_or_404(
        Tasks, id=id, user=request.user
    )  # 自分のタスクのみ削除可能

    task.delete()
    return redirect("task_list")


# タスク編集
def taskedit_view(request, id):
    if not request.user.is_authenticated:
        return redirect("login")  # 未ログインならログインページへリダイレクト

    task = get_object_or_404(
        Tasks, id=id, user=request.user
    )  # 自分のタスクのみ編集可能

    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)  # 既存のデータをフォームに適用
        if form.is_valid():
            form.save()
            return redirect("task_list")  # 一覧ページへリダイレクト

    else:
        form = TaskForm(instance=task)  # 既存のデータをフォームにセット

    return render(request, "todoform.html", {"form": form, "task": task})


def statusedit_view(request, id):
    if not request.user.is_authenticated:
        return redirect("login")  # 未ログインならログインページへリダイレクト

    task = get_object_or_404(
        Tasks, id=id, user_id=request.user.user_id
    )  # 自分のタスクのみ編集可能

    if request.method == "POST":
        task.is_completed = not task.is_completed
        task.save(update_fields=["is_completed", "update_at"])

    return redirect("task_list")  # 一覧ページへリダイレクト


# Todoタイトル検索、完了未完了ソート機能
def tasksearch_view(request):
    query = request.GET.get("q", "")  # 検索キーワード取得
    status = request.GET.get("status", "")  # 完了・未完了の状態を取得

    tasks = Tasks.objects.filter(
        user=request.user
    )  # ユーザーに関連するタスクのみをフィルタリングして取得

    if query:
        tasks = tasks.filter(
            title__icontains=query
        )  # 検索ワードが空でない場合、タイトルに部分一致するタスクをフィルタリングして取得

    # 完了・未完了の状態が指定されている場合、その状態でフィルタリング
    if status == "completed":
        tasks = tasks.filter(is_completed=True)  # 完了タスクのみ
    elif status == "incomplete":
        tasks = tasks.filter(is_completed=False)  # 未完了タスクのみ

    tasks = tasks.order_by("deadline")  # タスクを締切日順に昇順に並び替え

    return render(
        request, "todo.html", {"tasks": tasks, "query": query, "status": status}
    )  # tasks（タスク一覧）、query（検索キーワード）、status（選択された状態）をコンテキストとしてtodo.htmlへ渡してレンダリング

templates/base.html
{% load static %} {% load widget_tweaks %}

<!doctype html>
<html lang="ja" class="overflow-hidden">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>StudyHub</title>

    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAuDf-txlL1EEte-Iqolx0CvtvxazFkF6k&callback=initMap"
      async
      defer
    ></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=Rampart+One&display=swap"
      rel="stylesheet"
    />

    {% block header %}{% endblock header %}

    <!-- <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    /> -->
  </head>

  <body class="h-dvh w-full overflow-hidden bg-baseColor">
    <header
      id="menubar"
      class="flex h-20 items-center bg-menuColor max-md:justify-between"
    >
      <a
        href="/"
        class="pb-2 pl-5 pr-10 font-rampartOne text-4xl text-baseColor"
        >StudyHub</a
      >
      <button
        type="button"
        class="mr-5 flex flex-col space-y-2 md:hidden"
        id="hamburger"
      >
        <span class="h-0.5 w-8 bg-baseColor duration-150"></span>
        <span class="h-0.5 w-8 bg-baseColor duration-150"></span>
        <span class="h-0.5 w-8 bg-baseColor duration-150"></span>
      </button>
      <nav
        id="nav"
        class="nav-md right-[-100%] z-40 md:flex md:w-full md:text-baseColor"
      >
        <ul class="flex h-full w-full items-center max-md:flex-col">
          <li class="nav-item">
            <a
              onclick="resetLocalStorage()"
              href="/"
              class="flex h-full items-center px-6 font-kosugiMaru text-2xl"
              >HOME</a
            >
          </li>
          <li class="nav-item">
            <a
              href="{% url 'map:search' %}"
              class="flex h-full items-center px-6 font-kosugiMaru text-2xl"
              >検索</a
            >
          </li>
          <li class="nav-item">
            <a
              href="{% url 'task_list'%}"
              class="flex h-full items-center px-6 font-kosugiMaru text-2xl"
              >ToDo</a
            >
          </li>
          <li class="nav-item">
            <a
              href="{% url 'mypage' user.user_id %}"
              class="flex h-full items-center px-4 font-kosugiMaru text-2xl"
              >マイページ</a
            >
          </li>
          <li class="nav-item ml-auto">
            <form
              name="logoutForm"
              method="POST"
              action="{% url 'logout' %}"
              class="flex h-full items-center justify-center"
            >
              {% csrf_token %}
              <button
                type="button"
                onclick="resetSessionStorage()"
                class="flex h-full items-center justify-center p-5 hover:bg-highlightColor"
              >
                <ion-icon
                  name="exit-outline"
                  class="hidden pl-3 text-4xl md:flex"
                ></ion-icon>
                <p class="px-8 font-kosugiMaru text-2xl font-medium md:hidden">
                  ログアウト
                </p>
              </button>
            </form>
          </li>
        </ul>
      </nav>
    </header>

    {% block body %} {% endblock body %}

    <div
      id="timer-container"
      class="absolute inset-x-0 bottom-0 z-40 mx-auto flex w-[20%] min-w-64 max-w-fit items-center sm:right-5 sm:mr-0"
    >
      <img
        id="timer-image"
        src="{% static 'images/timer.png' %}"
        alt="タイマー画像"
        class=""
      />
      <div
        id="timer-controls"
        class="absolute flex h-[80%] w-full items-center justify-between px-[3%]"
        data-url="{% url 'timer:update' %}"
      >
        <div
          id="timer-display"
          class="flex h-full w-[65%] flex-col items-center justify-center rounded-md bg-white"
        >
          <p
            id="time-edit-error"
            class="fixed mb-[4.5rem] hidden text-xs text-card-button-red"
          >
            半角数字で入力してください
          </p>

          {% if is_working and is_pomodoro %}
          <p class="fixed mb-[4.5rem] animate-pulse text-xs">Work Time</p>
          {% elif not is_working and is_pomodoro %}
          <p class="fixed mb-[4.5rem] animate-pulse text-xs">Break Time</p>
          {% endif %}
          <!-- prettier-ignore -->
          <p
            id="time"
            class="block text-4xl font-medium"
            data-working="{{ is_working }}"
            data-pomodoro="{{ is_pomodoro }}"
          >{{ set_time }}</p>
          <div
            id="edit-time"
            class="hidden w-11/12 items-center justify-center"
          >
            <input
              name="hours"
              type="text"
              pattern="^[1-9][0-9]*$"
              inputmode="numeric"
              maxlength="2"
              value="00"
              class="input-time w-12 px-0.5 py-1 text-center text-4xl font-medium"
            />
            <p class="text-center text-4xl font-medium">:</p>
            <input
              name="minutes"
              type="text"
              pattern="^[1-9][0-9]*$"
              inputmode="numeric"
              maxlength="2"
              value="00"
              class="input-time w-12 px-0.5 py-1 text-center text-4xl font-medium"
            />
            <p class="text-center text-4xl font-medium">:</p>
            <input
              name="seconds"
              type="text"
              pattern="^[1-9][0-9]*$"
              inputmode="numeric"
              maxlength="2"
              value="00"
              class="input-time w-12 px-0.5 py-1 text-center text-4xl font-medium"
            />
          </div>
        </div>
        <div class="flex h-full w-[30%] flex-col justify-between gap-3 py-[2%]">
          <button
            id="timer-start-btn"
            onclick="startTimer()"
            class="flex h-full w-full items-center justify-center rounded-full bg-white"
          >
            START
          </button>
          <button
            id="timer-stop-btn"
            onclick="stopTimer()"
            class="hidden h-full w-full items-center justify-center rounded-full bg-white"
          >
            STOP
          </button>
          <button
            id="timer-finish-btn"
            onclick="finishTimer()"
            class="flex h-full w-full items-center justify-center rounded-full bg-white"
          >
            FINISH
          </button>
        </div>
      </div>
    </div>

    <div id="timer-modal" class="modal-container hidden">
      <div class="timer-modal-overlay modal-overlay"></div>
      <div
        class="z-50 flex h-fit w-fit flex-col items-center justify-center rounded border-2 border-card-border bg-card"
      >
        <form
          name="saveTimeForm"
          action="{% url 'timer:save' %}"
          class="flex flex-col items-center justify-center"
          method="post"
        >
          <h2 class="mx-12 my-6 text-2xl">お疲れさまでした！</h2>
          <p>今回の勉強時間</p>
          <!-- prettier-ignore -->
          {% csrf_token %}
          {{ timer_modal_form.count_time|add_class:"mt-1 mb-6 text-xl font-bold text-center"|attr:"id:registered-time" }}

          <div class="mb-6 flex w-full max-w-sm justify-center gap-8">
            <button
              type="button"
              onclick="saveTime()"
              class="h-8 w-24 rounded bg-card-button-red"
            >
              登録
            </button>
            <button
              type="button"
              onclick="toggleTimerModal()"
              class="h-8 w-24 rounded bg-stone-50"
            >
              キャンセル
            </button>
          </div>
          {% if is_working and is_pomodoro %}
          <p class="mx-6 my-3">[登録]を押すと休憩時間のタイマーを開始します</p>
          {% endif %}
        </form>
      </div>
    </div>

    <div id="breaktime-modal" class="modal-container hidden">
      <div class="time-modal-overlay modal-overlay"></div>
      <div
        class="z-50 flex h-fit w-fit flex-col items-center justify-center rounded border-2 border-card-border bg-card"
      >
        <form
          name="breakTimeForm"
          action="{% url 'timer:save' %}"
          class="flex flex-col items-center justify-center gap-6"
          method="post"
        >
          {% csrf_token %}
          <h2 class="mx-24 mt-12 text-2xl">休憩終了！</h2>
          <p>作業時間を開始します</p>

          <div class="mb-12 flex w-full max-w-sm justify-center gap-8">
            <button
              type="button"
              onclick="saveTime()"
              class="h-8 w-24 rounded bg-card-button-red"
            >
              開始
            </button>
            <button
              type="button"
              onclick="toggleBreakTimeModal()"
              class="h-8 w-24 rounded bg-stone-50"
            >
              まだ
            </button>
          </div>
        </form>
      </div>
    </div>

    {% block modal %} {% endblock modal %}

    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>

    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/timer.js' %}"></script>
  </body>
</html>

templates/main.html
{% extends 'base.html' %} {% load static %} {% block header %}
<script
  src="https://maps.googleapis.com/maps/api/js?key=API_KEY&callback=initMap"
  async
  defer
></script>
<script src="{% static 'js/map-display.js' %}" defer></script>
<script src="{% static 'js/map.js' %}" defer></script>

{% endblock header %}{% block body %}
<div
  class="background flex h-[calc(100dvh-5rem)] min-w-full flex-col items-center overflow-hidden pb-32 pt-[2%]"
>
  <div
    class="hidden-scrollbar flex h-full w-full flex-col items-center max-sm:overflow-y-auto sm:flex-row sm:justify-evenly"
  >
    <div class="main-content-box">
      <h1 class="mb-5 mt-2 text-center font-kosugiMaru text-2xl font-bold">
        近くのStudySpot
      </h1>
      {% if results %}
      <!-- prettier-ignore -->
      {% for result in results %}
      {% with lat=result.lat lng=result.lng place_id=result.place_id %}
      <a
        href="{% url 'map:search_detail' %}?lat={{ lat }}&lng={{ lng }}&place_id={{ place_id }}"
        class="mb-4 h-full w-full truncate"
      >
        <div
          class="flex h-[90%] w-full flex-col justify-evenly rounded-lg border-4 border-card-border bg-white px-4 py-4 text-center hover:bg-stone-100"
        >
          <h3 class="truncate text-center font-kosugiMaru font-semibold">
            {{ result.name }}
          </h3>
          <p class="truncate font-kosugiMaru font-medium max-sm:hidden">
            {{ result.vicinity }}
          </p>
          <div class="flex justify-center gap-8">
            <p class="font-kosugiMaru font-medium">
              <span class="text-yellow-400">★</span>{{ result.rating }}
            </p>
            <p class="font-kosugiMaru font-medium">
              {{ result.walking_distance }}
            </p>
          </div>
        </div>
      </a>
      {% endwith %} {% endfor %} {% endif %}
    </div>

    <div class="main-content-box">
      <h1 class="mb-5 mt-2 text-center font-kosugiMaru text-2xl font-bold">
        急ぎのToDo
      </h1>
      {% for task in tasks %}
      <a
        href="{% url 'task_detail' task.id %}"
        class="mb-4 h-full w-full truncate"
      >
        <div
          class="flex h-[90%] flex-col items-center justify-center space-y-1 rounded-lg border-4 border-card-border bg-white px-4 py-4 text-center hover:bg-stone-100"
        >
          <h3 class="truncate text-center font-kosugiMaru font-semibold">
            {{ task.title }}
          </h3>
          <p class="font-mediu font-kosugiMaru">
            {{ task.deadline|date:"Y/m/d" }} まで
          </p>
        </div>
      </a>
      {% endfor %}
    </div>

    <img
      class="main-character absolute bottom-4 left-auto max-sm:hidden xl:static xl:h-56 xl:w-56"
      src="/static/images/doubutu_carrybackwomotteryokousurutukinowakuma.png"
      alt=""
    />
  </div>
</div>
{% endblock body %}

templates/search.html
{% extends 'base.html' %} {% load static %} {% block header %}
<script src="{% static 'js/map.js' %}" defer></script>
<script src="{% static 'js/map-display.js' %}" defer></script>
{% endblock header %} {% block body %}

<div
  class="container flex h-[calc(100dvh-5rem)] min-w-full flex-wrap items-center justify-evenly md:flex-nowrap"
>
  <div id="map" class="rounded-lg border-4 border-card-border"></div>
  <img
    class="search-character absolute left-[44.8rem] top-[7.6rem] hidden"
    src="/static/images/doubutu_madokaraamewomirutukinowaguma.png"
    alt=""
  />
  <div class="h-[80%] w-[43%]">
    <form
      id="searchForm"
      class="flex h-[90%] w-full flex-col gap-16 rounded-lg border-4 border-card-border bg-card px-5"
      action="{% url 'map:search_result' %}"
      method="GET"
    >
      <div class="flex h-full w-full flex-col gap-16">
        <div>
          <input
            name="keyword"
            type="text"
            class="mt-16 h-14 w-full rounded-xl border-4 border-card-border pl-3"
            placeholder="検索ワード"
          />
        </div>
        <div>
          <div class="flex justify-evenly">
            <label class="inline-flex cursor-pointer items-center">
              <span class="mr-3 font-kosugiMaru text-2xl">カフェ</span>
              <input
                type="radio"
                name="place"
                value="cafe"
                class="peer sr-only"
                checked
              />
              <div
                class="peer relative h-6 w-11 rounded-full bg-gray-500 after:absolute after:start-[2px] after:top-0.5 after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:ring-4 peer-focus:ring-blue-300 rtl:peer-checked:after:-translate-x-full dark:border-gray-600 dark:bg-gray-700 dark:peer-checked:bg-blue-600 dark:peer-focus:ring-blue-800"
              ></div>
            </label>
            <label class="inline-flex cursor-pointer items-center">
              <span class="mr-3 font-kosugiMaru text-2xl">図書館</span>
              <input
                type="radio"
                name="place"
                value="library"
                class="peer sr-only"
              />
              <div
                class="peer relative h-6 w-11 rounded-full bg-gray-500 after:absolute after:start-[2px] after:top-0.5 after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:ring-4 peer-focus:ring-blue-300 rtl:peer-checked:after:-translate-x-full dark:border-gray-600 dark:bg-gray-700 dark:peer-checked:bg-blue-600 dark:peer-focus:ring-blue-800"
              ></div>
            </label>
            <label class="inline-flex cursor-pointer items-center">
              <span class="mr-3 font-kosugiMaru text-2xl">大学</span>
              <input
                type="radio"
                name="place"
                value="university"
                class="peer sr-only"
              />
              <div
                class="peer relative h-6 w-11 rounded-full bg-gray-500 after:absolute after:start-[2px] after:top-0.5 after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-blue-600 peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:ring-4 peer-focus:ring-blue-300 rtl:peer-checked:after:-translate-x-full dark:border-gray-600 dark:bg-gray-700 dark:peer-checked:bg-blue-600 dark:peer-focus:ring-blue-800"
              ></div>
            </label>
          </div>
        </div>
        <div>
          <input
            name="distance"
            type="range"
            min="1000"
            step="1000"
            max="5000"
            class="slider w-full"
          />
          <div
            class="flex w-full justify-between px-2 font-kosugiMaru text-xl font-bold"
          >
            <span>1km</span>
            <span>2km</span>
            <span>3km</span>
            <span>4km</span>
            <span>5km</span>
          </div>
        </div>
      </div>
      <button
        class="mb-10 w-full rounded-xl bg-card-button py-4 font-kosugiMaru text-xl font-bold text-white underline"
        type="submit"
      >
        検索
      </button>
    </form>
  </div>
</div>
<script>
  document.getElementById("searchForm").addEventListener("submit", function () {
    const selectedTypes = Array.from(
      document.querySelectorAll('input[name="place"]:checked')
    ).map((input) => input.value); // カンマ区切りで送信
    const distance = Array.from(
      document.querySelectorAll('input[name="distance"]')
    ).map((input) => input.value);

    // localStorage に保存
    localStorage.setItem("selectedTypes", JSON.stringify(selectedTypes));
    localStorage.setItem("distance", JSON.stringify(distance));
  });
</script>

{% endblock body %}

templates/search_detail.html
{% extends 'base.html' %}{% load static %} {% block header %}
<!-- 詳細画面の HTML -->
<script src="{% static 'js/map-display-detail.js' %}" defer></script>
{% endblock header %} {% block body %}
<div
  class="container flex h-[calc(100dvh-5rem)] min-w-full flex-wrap items-center justify-evenly md:flex-nowrap"
>
  <div id="map" class="rounded-lg border-4 border-card-border"></div>
  <div class="map-card">
    <div
      class="flex h-[90%] flex-col justify-evenly rounded-lg border-4 border-card-border bg-card p-10"
    >
      <h1 class="truncate font-kosugiMaru text-4xl font-bold">
        {{ details.name }}
      </h1>
      <div>
        <p class="truncate font-kosugiMaru text-2xl font-medium">
          住所：{{ details.vicinity }}
        </p>
      </div>
      <p
        class="w-full truncate whitespace-nowrap font-kosugiMaru text-2xl font-medium"
      >
        現在地からの距離(徒歩)：{{ distance }}
      </p>
      <p class="truncate font-kosugiMaru text-2xl font-medium">
        レビュー：<span class="text-yellow-400">★</span> {{ details.rating }}
      </p>
      <div class="gap-3">
        <p class="mb-2 text-2xl font-medium">営業時間：</p>
        <div class="grid grid-cols-2">
          {% for day in details.opening_hours.weekday_text %}

          <p class="mb-2 truncate font-kosugiMaru text-xl">{{ day }}</p>
          {% endfor %}
        </div>
      </div>
      <p class="w-full truncate font-kosugiMaru text-xl font-bold">
        <a href="{{ details.website }}" class="text-blue-400 underline"
          >{{ details.website }}</a
        >
      </p>
    </div>
    <img
      class="search-detail-character hidden"
      Z
      src="/static/images/doubutu_tukinowaguma_valley3.png"
      alt=""
    />
  </div>
</div>

{% endblock body %}

templates/search_result.html
{% extends 'base.html' %} {% load static %} {% block header %}
<script src="{% static 'js/map.js' %}" defer></script>
<script src="{% static 'js/map-display.js' %}" defer></script>
{% endblock header %} {% block body %}

<div
  class="container flex h-[calc(100dvh-5rem)] min-w-full flex-wrap items-center justify-evenly md:flex-nowrap"
>
  <div id="map" class="rounded-lg border-4 border-card-border"></div>
  <div class="map-card">
    <div
      class="hidden-scrollbar flex h-[90%] flex-col space-y-3 overflow-y-auto"
    >
      {% if results %} {% for result in results %}
      <!-- prettier-ignore -->
      {% with lat=result.geometry.location.lat|stringformat:"s" lng=result.geometry.location.lng|stringformat:"s" place_id=result.place_id %}
      <a
        href="{% url 'map:search_detail' %}?lat={{ lat }}&lng={{ lng }}&place_id={{ place_id }}"
      >
        <div
          class="flex w-full items-center justify-between space-y-2 rounded-lg border-4 border-card-border bg-white px-4 py-4"
        >
          <div class="w-3/4">
            <h1 class="truncate font-kosugiMaru text-lg font-bold">
              {{ result.name }}
            </h1>
            <p class="truncate font-kosugiMaru text-lg">
              {{ result.vicinity }}
            </p>
            <p class="font-kosugiMaru text-lg">
              <span class="text-yellow-400">★</span>{{ result.rating }}
            </p>
          </div>
          <div class="ml-3">
            <p class="flex items-center justify-center font-kosugiMaru text-xl">
              {{ result.walking_distance }}
            </p>
          </div>
        </div>
      </a>
      {% endwith %} {% endfor %} {% else %}

      <div
        class="space-y-2 rounded-lg border-4 border-card-border bg-white px-4 py-4"
      >
        <h1 class="font-kosugiMaru text-lg font-bold">検索結果がありません</h1>
      </div>
      {% endif %}
    </div>
    <div
      class="absolute bottom-1 flex h-32 w-56 items-center justify-center overflow-hidden max-lg:hidden"
    >
      <img
        class="search-result-character object-cover"
        src="/static/images/doubutu_dokusyo_kuma.png"
        alt=""
      />
    </div>
  </div>
</div>

{% endblock body %}